# yaml_dir: ./data_info/data.yaml
# light_dir: /input/pihuaijin/datasets/sl_relight/sh_hdr
yaml_dir: /nas/home/hujunkang/data.yaml
light_dir: /nas/home/hujunkang/sh_hdr

epochs: 100
data_load_works: 4
save_fre: 5
lr: 0.0001